# -*- coding: utf-8 -*-
"""PP2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zaj4kP7thQsyHjEcltA0RvzqXwl0Q15w

Εισαγωγή βιβλιοθηκών
"""

import os
import numpy as np
import pandas as pd
from sklearn.datasets import load_files

# Ρυθμίσεις για να φαίνονται ολόκληρα τα κείμενα στο DataFrame
pd.set_option('display.max_colwidth', None)

print("Οι βιβλιοθήκες φορτώθηκαν επιτυχώς.")

"""Λήψη και αποσυμπίεση των δεδομένων"""

try:
  # URL του dataset από το Cornell
  dataset_url = "http://www.cs.cornell.edu/people/pabo/movie-review-data/review_polarity.tar.gz"

  # Κατέβασμα του αρχείου
  !wget -q {dataset_url} -O dataset.tar.gz

  # Αποσυμπίεση του αρχείου
  !tar -xzf dataset.tar.gz
  print("Η λήψη και αποσυμπίεση ολοκληρώθηκε.")
except Exception as err:
  print(f"Unexpected {err=}, {type(err)=}")

# Ελέγχουμε αν υπάρχει ο φάκελος txt_sentoken
if os.path.exists('txt_sentoken'):
    print("Βρέθηκε ο φάκελος δεδομένων: txt_sentoken")
else:
    print("Προσοχή: Κάτι πήγε στραβά με την αποσυμπίεση.")
    print("Προσπάθεια ανάγνωσης δεδομένων από τοπικό φάκελο.")

    try:
      from google.colab import drive
      drive.mount('/content/drive')
      filepath = "/content/drive/MyDrive/Colab Notebooks/Search Engines and Text Analysis/PP2/review_polarity/txt_sentoken"

      !cp -r "{filepath}" /content/
      print("Η ανάγνωση ολοκληρώθηκε!")
    except Exception:
      print("Τα δεδομένα δεν μπόρεσαν να αναγνωστούν.")

"""Φόρτωση των δεδομένων στη μνήμη και δημιουργία DataFrame"""

def load_dataset_to_dataframe(data_path):
    # Η load_files διαβάζει αυτόματα subfolders ως κατηγορίες
    # shuffle=True: Ανακατεύει τα δεδομένα (σημαντικό για την εκπαίδευση)
    # random_state=42: Για να έχουμε πάντα το ίδιο ανακάτεμα (αναπαραγωγιμότητα)
    data = load_files(data_path, encoding="utf-8", decode_error="replace", shuffle=True, random_state=42)

    # Δημιουργία Pandas DataFrame για ευκολότερη διαχείριση
    df = pd.DataFrame({
        'text': data.data,
        'label': data.target
    })

    return df

# Καλούμε τη συνάρτηση (ο φάκελος που αποσυμπιέστηκε λέγεται 'txt_sentoken')
df = load_dataset_to_dataframe('txt_sentoken')

print("Τα δεδομένα φορτώθηκαν στο DataFrame 'df'.")

"""Επισκόπηση των δεδομένων"""

# Εκτύπωση του πλήθους των δεδομένων
print(f"Συνολικό πλήθος κειμένων: {len(df)}")
print(f"Κατανομή κατηγοριών (0=Negative, 1=Positive):\n{df['label'].value_counts()}")

print("\n--- Δείγμα των πρώτων 5 εγγραφών ---")
display(df.head())

# Έλεγχος για τυχόν κενά δεδομένα
print(f"\nΚενά κείμενα: {df['text'].isnull().sum()}")

"""**Μέρος Α**

Προεπεξεργασία κειμένου
"""

import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

# Κατεβάζουμε τη λίστα με τις "κενές" λέξεις (the, is, at, etc.)
nltk.download('stopwords')

# Αρχικοποίηση εργαλείων
stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()

def clean_text(text):
    """
    Δέχεται ένα κείμενο (string) και επιστρέφει το καθαρισμένο κείμενο.
    Βήματα:
    1. Αφαίρεση HTML tags (αν υπάρχουν) και ειδικών χαρακτήρων.
    2. Μετατροπή σε πεζά (lowercase).
    3. Αφαίρεση σημείων στίξης και αριθμών.
    4. Αφαίρεση Stopwords.
    5. Stemming (μείωση λέξεων στη ρίζα τους).
    """
    # 1. Αφαίρεση μη αλφαβητικών χαρακτήρων (κρατάμε μόνο γράμματα)
    text = re.sub(r'[^a-zA-Z]', ' ', text)

    # 2. Μετατροπή σε πεζά
    text = text.lower()

    # 3. Tokenization (χωρισμός σε λίστα λέξεων)
    words = text.split()

    # 4 & 5. Αφαίρεση Stopwords και Stemming
    # Κρατάμε τη λέξη αν ΔΕΝ είναι στα stopwords, και της κάνουμε stem
    cleaned_words = [stemmer.stem(word) for word in words if word not in stop_words]

    # Ενωση ξανά σε string
    return ' '.join(cleaned_words)

# Εφαρμογή της συνάρτησης σε όλο το dataset
# (Αυτό μπορεί να πάρει λίγα δευτερόλεπτα)
print("Έναρξη καθαρισμού κειμένων...")
df['clean_text'] = df['text'].apply(clean_text)

print("Ο καθαρισμός ολοκληρώθηκε.")
print("\n--- Παράδειγμα Πριν και Μετά ---")
print("Original:", df['text'].iloc[0][:100])
print("Cleaned :", df['clean_text'].iloc[0][:100])

"""Word2Vec Transformer"""

!pip install gensim

from sklearn.base import BaseEstimator, TransformerMixin
from gensim.models import Word2Vec
from sklearn.preprocessing import MinMaxScaler

class Word2VecVectorizer(BaseEstimator, TransformerMixin):
    def __init__(self, vector_size=100, window=5, min_count=1):
        self.vector_size = vector_size
        self.window = window
        self.min_count = min_count
        self.model = None
        self.scaler = MinMaxScaler() # Όπως ζητάει η εκφώνηση (0-1 scaling)

    def fit(self, X, y=None):
        # Το Word2Vec θέλει λίστα από λίστες λέξεων (sentences)
        sentences = [text.split() for text in X]
        # Εκπαίδευση του μοντέλου
        self.model = Word2Vec(sentences, vector_size=self.vector_size,
                              window=self.window, min_count=self.min_count, workers=4)
        return self

    def transform(self, X):
        # Mean Pooling: Μέσος όρος των διανυσμάτων των λέξεων για κάθε κείμενο
        words_lists = [text.split() for text in X]
        vectors = []
        for words in words_lists:
            word_vectors = [self.model.wv[w] for w in words if w in self.model.wv]
            if len(word_vectors) > 0:
                # Μέσος όρος (axis=0)
                vectors.append(np.mean(word_vectors, axis=0))
            else:
                # Αν δεν βρεθούν λέξεις (σπάνιο), βάζουμε μηδενικό διάνυσμα
                vectors.append(np.zeros(self.vector_size))

        # Μετατροπή σε numpy array
        vectors = np.array(vectors)

        # Scaling στο 0-1 (Απαραίτητο για Naive Bayes)
        return self.scaler.fit_transform(vectors)

print("Η κλάση Word2VecVectorizer είναι έτοιμη.")

"""Ορισμός μοντέλων και 5-Fold Cross Validation"""

# Ορισμός Μοντέλων και Cross-Validation
from sklearn.model_selection import cross_validate
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB, BernoulliNB

# Ορίζουμε τα δεδομένα εισόδου και τις ετικέτες
X = df['clean_text']
y = df['label']

# Λίστα με τα Pipelines (Συνδυασμοί Κ και Ε της εκφώνησης)
pipelines = {
    # Κ1. Multinomial NB + Ε2. Πλήθος εμφανίσεων (Counts)
    "K1_E2 (MNB + Counts)": Pipeline([
        ('vect', CountVectorizer()),
        ('clf', MultinomialNB())
    ]),

    # Κ1. Multinomial NB + Ε3. TF-IDF
    "K1_E3 (MNB + TF-IDF)": Pipeline([
        ('vect', TfidfVectorizer()),
        ('clf', MultinomialNB())
    ]),

    # Κ2. Bernoulli NB + Ε1. Δυαδική (Binary)
    # Προσοχή: binary=True στον CountVectorizer
    "K2_E1 (Bernoulli + Binary)": Pipeline([
        ('vect', CountVectorizer(binary=True)),
        ('clf', BernoulliNB())
    ]),

    # Κ3. Boolean (Binarized) MNB + Ε1. Δυαδική (Binary)
    # Χρησιμοποιούμε MultinomialNB αλλά με binary δεδομένα
    "K3_E1 (Bin MNB + Binary)": Pipeline([
        ('vect', CountVectorizer(binary=True)),
        ('clf', MultinomialNB())
    ]),

    # Ε4. Word2Vec + Mean Pooling + MinMaxScaler (για Κ1 - MNB)
    "K1_E4 (MNB + Word2Vec)": Pipeline([
        ('w2v', Word2VecVectorizer(vector_size=100)),
        ('clf', MultinomialNB())
    ])
}

# Λεξικό για να αποθηκεύσουμε τα αποτελέσματα
results = {}

print("Ξεκινάει το 5-fold Cross-Validation για όλα τα μοντέλα...\n")

for name, pipe in pipelines.items():
    print(f"Running: {name} ...")
    # cross_validate υπολογίζει αυτόματα τα metrics σε 5 folds
    scores = cross_validate(pipe, X, y, cv=5,
                            scoring=['accuracy', 'precision_macro', 'recall_macro', 'f1_macro'])

    # Αποθηκεύουμε τους μέσους όρους
    results[name] = {
        'Accuracy': scores['test_accuracy'].mean(),
        'Precision': scores['test_precision_macro'].mean(),
        'Recall': scores['test_recall_macro'].mean(),
        'F1-Score': scores['test_f1_macro'].mean()
    }

# Μετατροπή αποτελεσμάτων σε DataFrame για ωραία εκτύπωση
results_df = pd.DataFrame(results).T
print("\n=== Τελικά Αποτελέσματα (Baselines) ===")
display(results_df.sort_values(by='Accuracy', ascending=False))

"""**Μέρος Β**

*   Α) Διαχείριση άρνησης
"""

import re

def clean_text_with_negation(text):
    # 1. Αρχικά κάνουμε τα βασικά (lowercase)
    text = text.lower()

    # 2. Χωρίζουμε το κείμενο σε λέξεις (tokens), κρατώντας και τα σημεία στίξης
    # Αυτό το regex χωρίζει λέξεις και κρατάει τα σημεία στίξης ξεχωριστά
    tokens = re.findall(r"[\w']+|[.,!?;]", text)

    # Λίστα με λέξεις που ξεκινάνε την άρνηση
    negation_triggers = {"not", "no", "never", "n't", "cannot", "nothing", "nowhere"}

    final_tokens = []
    negation_flag = False

    for word in tokens:
        if word in [".", ",", "!", "?", ";"]:
            negation_flag = False
            continue # Δεν κρατάμε το σημείο στίξης (προαιρετικό)


        if negation_flag:
            word = "NOT_" + word


        # (Ελέγχουμε αν η λέξη είναι trigger ή αν τελειώνει σε n't π.χ. don't)
        if word in negation_triggers or word.endswith("n't"):
            negation_flag = True

        # Προσθέτουμε τη λέξη (αλλαγμένη ή όχι) στη λίστα
        final_tokens.append(word)

    return " ".join(final_tokens)

# --- Δοκιμή για να δούμε αν δουλεύει ---
sample_sentence = "I did not like this movie, but the acting was good."
print("Αρχική πρόταση:", sample_sentence)
print("Μετά την άρνηση:", clean_text_with_negation(sample_sentence))

"""

*   Β) Στάθμιση με POS
"""

import nltk
from nltk import pos_tag
from nltk.tokenize import word_tokenize

# Κατεβάζουμε τα απαραίτητα αρχεία για να ξέρει το NLTK τι είναι ρήμα, επίθετο κτλ.
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('punkt_tab') # Χρειάζεται για το tokenization

def clean_text_with_pos(text):
    # 1. Tokenization: Χωρίζουμε το κείμενο σε λέξεις
    words = word_tokenize(text)

    # 2. POS Tagging: Βρίσκουμε τι μέρος του λόγου είναι κάθε λέξη
    # Επιστρέφει ζευγάρια: [('movie', 'NN'), ('is', 'VBZ'), ('good', 'JJ')]
    tagged_words = pos_tag(words)

    final_tokens = []

    # Λίστα με ετικέτες που μας ενδιαφέρουν (JJ=Adjective, RB=Adverb)
    # JJ, JJR, JJS = Επίθετα (απλό, συγκριτικό, υπερθετικό)
    # RB, RBR, RBS = Επιρρήματα
    target_tags = {'JJ', 'JJR', 'JJS', 'RB', 'RBR', 'RBS'}

    for word, tag in tagged_words:
        # Καθαρίζουμε λίγο τη λέξη (lowercase)
        clean_word = word.lower()

        # Αν είναι γράμμα (όχι σημείο στίξης)
        if clean_word.isalpha():
            final_tokens.append(clean_word) # Προσθέτουμε τη λέξη μία φορά (βάρος 1)

            # Αν είναι Επίθετο ή Επίρρημα, την ξαναπροσθέτουμε (βάρος 1+1=2)
            if tag in target_tags:
                final_tokens.append(clean_word)

    return " ".join(final_tokens)

# --- Δοκιμή ---
sample_pos = "The movie was incredibly boring."
print("Αρχική πρόταση:", sample_pos)
print("Μετά το POS weighting:", clean_text_with_pos(sample_pos))

"""

*   Γ) Στάθμιση με βάρη βάση της θέσης της πρότασης

"""

# Υλοποίηση Στάθμισης Θέσης (Position Weighting)
from nltk.tokenize import sent_tokenize

nltk.download('punkt_tab')

def clean_text_with_position(text):
    # 1. Χωρίζουμε το κείμενο σε προτάσεις
    sentences = sent_tokenize(text)

    if not sentences:
        return ""

    # Ορίζουμε ποιες προτάσεις είναι σημαντικές (1η και Τελευταία)
    first_sentence = sentences[0]
    last_sentence = sentences[-1] if len(sentences) > 1 else ""

    # 2. Φτιάχνουμε το τελικό κείμενο:
    # Αρχικό κείμενο (όλα με βάρος 1) + 1η Πρόταση (ξανά) + Τελευταία Πρόταση (ξανά)
    augmented_text = text + " " + first_sentence + " " + last_sentence

    # 3. Κάνουμε έναν απλό καθαρισμό (lowercase κτλ) στο τελικό αποτέλεσμα
    # Χρησιμοποιούμε regex για να κρατήσουμε μόνο λέξεις
    final_tokens = re.findall(r'\w+', augmented_text.lower())

    return " ".join(final_tokens)

# --- Δοκιμή ---
sample_pos = "I hated this movie. The plot was boring. But the actors were nice. Do not watch it."
print("Αρχικό κείμενο:", sample_pos)
print("\n--- Αποτέλεσμα ---")
print(clean_text_with_position(sample_pos))

"""Προετοιμασία των δεδομένων"""

# Συνάρτηση που τα συνδυάζει όλα (Σενάριο 5: Baseline + Όλα μαζί)
def clean_text_all(text):
    # 1. Βάρη Θέσης (Position)
    step1 = clean_text_with_position(text)
    # 2. Βάρη POS (Part of Speech)
    step2 = clean_text_with_pos(step1)
    # 3. Διαχείριση Άρνησης (Negation)
    step3 = clean_text_with_negation(step2)
    return step3

print("Δημιουργία των παραλλαγών κειμένου.")

# Δημιουργούμε νέες στήλες στο DataFrame για κάθε σενάριο
# Σημείωση: Το 'clean_text' (Baseline) το έχουμε ήδη από το Μέρος Α.

# Σενάριο 2: Negation
df['text_negation'] = df['text'].apply(clean_text_with_negation)
print("- Ολοκληρώθηκε η Άρνηση.")

# Σενάριο 3: POS
df['text_pos'] = df['text'].apply(clean_text_with_pos)
print("- Ολοκληρώθηκε το POS weighting.")

# Σενάριο 4: Position
df['text_position'] = df['text'].apply(clean_text_with_position)
print("- Ολοκληρώθηκε το Position weighting.")

# Σενάριο 5: All Combined
df['text_all'] = df['text'].apply(clean_text_all)
print("- Ολοκληρώθηκαν όλα μαζί.")

print("\nΔείγμα από 'All Combined':")
print(df['text_all'].iloc[0][:150])

"""5-fold Cross-Validation"""

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import cross_validate
import pandas as pd

# Ορίζουμε το βασικό μας μοντέλο (Baseline Classifier)
# Χρησιμοποιούμε CountVectorizer γιατί θέλουμε να μετρήσουμε τα διπλάσια tokens που δημιουργήσαμε
pipeline = Pipeline([
    ('vect', CountVectorizer(min_df=2)), # min_df=2: αγνοούμε λέξεις που εμφανίζονται μόνο 1 φορά
    ('clf', MultinomialNB())
])

# Λίστα με τα σενάρια και τις αντίστοιχες στήλες δεδομένων
scenarios = {
    "1. Baseline (Simple Clean)": 'clean_text',
    "2. Baseline + Negation": 'text_negation',
    "3. Baseline + POS Weighting": 'text_pos',
    "4. Baseline + Position Weighting": 'text_position',
    "5. Baseline + ALL Combined": 'text_all'
}

results_b = {}

print("Εκτέλεση πειραμάτων για το Μέρος Β...\n")

for name, col_name in scenarios.items():
    print(f"Running: {name}...")

    # Παίρνουμε τα δεδομένα της συγκεκριμένης παραλλαγής
    X_scenario = df[col_name]
    y = df['label']

    # Τρέχουμε Cross-Validation
    scores = cross_validate(pipeline, X_scenario, y, cv=5,
                            scoring=['accuracy', 'precision_macro', 'recall_macro', 'f1_macro'])

    # Αποθηκεύουμε
    results_b[name] = {
        'Accuracy': scores['test_accuracy'].mean(),
        'Precision': scores['test_precision_macro'].mean(),
        'Recall': scores['test_recall_macro'].mean(),
        'F1-Score': scores['test_f1_macro'].mean()
    }

# Εμφάνιση αποτελεσμάτων
results_df_b = pd.DataFrame(results_b).T
print("\n=== Τελικά Αποτελέσματα Μέρους Β (Γλωσσικοί Κανόνες) ===")
display(results_df_b.sort_values(by='Accuracy', ascending=False))

"""Αποθήκευση των αρχείων σε αρχείο Excel"""

# Αποθήκευση αποτελεσμάτων σε αρχεία
from google.colab import files
import pandas as pd

print("Ετοιμασία αρχείων για κατέβασμα...")

# --- Επιλογή 1: Αποθήκευση σε Excel (Προτείνεται) ---
# Θα φτιάξουμε ένα αρχείο 'results_all.xlsx' που θα έχει δύο καρτέλες
excel_filename = 'results_all.xlsx'

# Χρησιμοποιούμε τον ExcelWriter για να γράψουμε σε πολλαπλά sheets
with pd.ExcelWriter(excel_filename) as writer:
    # Αποθήκευση του Μέρους Α (αν υπάρχει το results_df)
    if 'results_df' in locals():
        results_df.sort_values(by='Accuracy', ascending=False).to_excel(writer, sheet_name='Part A - Baselines')

    # Αποθήκευση του Μέρους Β (αν υπάρχει το results_df_b)
    if 'results_df_b' in locals():
        results_df_b.sort_values(by='Accuracy', ascending=False).to_excel(writer, sheet_name='Part B - Linguistics')

print(f"Το αρχείο {excel_filename} δημιουργήθηκε.")

# Εντολή για να κατέβει το αρχείο στον υπολογιστή σου
files.download(excel_filename)