# -*- coding: utf-8 -*-
"""Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FXIEc3BskCLZB1Tr3ILnqEAV1ecCreA_

**Βήμα 1ο**: Ανάγνωση δεδομένων
"""

import pandas as pd
import numpy as np
from sklearn.datasets import load_diabetes

# Εδώ θα φορτώσουμε τα δεδομένα, με την εντολή που αναφέρει η εκφώνηση
diabetes_data = load_diabetes(as_frame=True, scaled=False)
# Επεξήγηση παραμέτρων
# as_frame=True: Επιστρέφει τα δεδομένα σε δομή που περιέχει Pandas DataFrame.
# scaled=False: Φορτώνει τα πρωτογενή δεδομένα (όχι κανονικοποιημένα).

# Μετατροπή σε DataFrame
df = diabetes_data.frame

# Εκτύπωση επιτυχούς ανάγνωσης
print("Data loaded successfully!\n")

# Ενδεικτική εκτύπωση των 5 πρώτων γραμμών των δεδομένων
print(df.head())

# Σύντομη περιγραφή των δεδομένων με στατιστικά που είναι χρήσιμα για την περιγραφή του DataSet
df.describe()

"""**Βήμα 2ο**: Εκτύπωση εύρους τιμών για μία στήλη του DataFrame"""

# Διαλέγουμε την στήλη
column_name = 'target'
data_range = df[column_name].max() - df[column_name].min()

print(f"--- Range Analysis for column: {column_name} ---")
print(f"Max Value: {df[column_name].max()}")
print(f"Min Value: {df[column_name].min()}")
print(f"Range (Max - Min): {data_range}")

"""**Βήμα 3ο**: Έλεγχος NaN τιμών και απομάκρυνση (εάν βρεθούν)"""

print("--- NaN Check ---")
if df.isnull().values.any():
    print("NaN values found. Removing corresponding rows...")
    initial_shape = df.shape

    # Απομάκρυνση των γραμμών με NaN
    df = df.dropna()

    print(f"Original shape: {initial_shape}")
    print(f"Shape after dropping NaNs: {df.shape}")
else:
    print("No NaN values found in the dataset.")

"""**Βήμα 4ο**: Εκτύπωση γραφήματος συχνοτήτων για την στήλη "target"
"""

import matplotlib.pyplot as plt

# Δημιουργία του figure και του άξονα
plt.figure(figsize=(10, 6))

# Δημιουργία ιστογράμματος
# bins=30: Χωρίζουμε το εύρος τιμών σε 30 ίσα διαστήματα για καλή ανάλυση
# edgecolor='black': Προσθέτουμε περίγραμμα για να ξεχωρίζουν οι μπάρες
plt.hist(df['target'], bins=30, color='limegreen', edgecolor='black')

# Προσθήκη ετικετών και τίτλου
plt.title('Κατανομή της μεταβλητής "Target" (Εξέλιξη ασθένειας)', fontsize=14)
plt.xlabel('Μεταβλητή "target" (Ποσοτική μέτρηση για την εξέλιξη της ασθένειας)', fontsize=12)
plt.ylabel('Συχνότητα (Πλήθος ασθενών)', fontsize=12)

# Εμφάνιση πλέγματος για ευκολότερη ανάγνωση
plt.grid(axis='y', alpha=0.75)

# Εμφάνιση του γραφήματος
plt.show()

"""**Βήμα 5ο**: Κανονικοποίηση δεδομένων με την χρήση του Min-Max scaling"""

from sklearn.preprocessing import MinMaxScaler

# X: Δεδομένα Εισόδου. Όλες οι στήλες εκτός από την 'target'
# y: Δεδομένα Εξόδου. Μόνο η στήλη 'target'
X = df.drop(columns=['target'])
y = df['target']

# Δημιουργία ξεχωριστών Scalers
# scaler_X: Για τα 10 χαρακτηριστικά (input)
# scaler_y: Για τη μεταβλητή στόχο (output)
scaler_X = MinMaxScaler()
scaler_y = MinMaxScaler()

# Εφαρμογή του Scaling (Fit & Transform)
# Το fit υπολογίζει τα Min/Max, το transform κάνει την πράξη
X_scaled = scaler_X.fit_transform(X)

# Η y είναι Series (1D), αλλά ο scaler θέλει 2D array.
# Χρησιμοποιούμε το .values.reshape(-1, 1) για να την κάνουμε στήλη.
y_scaled = scaler_y.fit_transform(y.values.reshape(-1, 1))

# Μετατρέπουμε το y_scaled ξανά σε 1D array για να βολεύει στα μοντέλα (flatten)
y_scaled = y_scaled.flatten()

# Εκτύπωση για επιβεβαίωση
print("--- Normalization Complete ---")
print(f"X_scaled range: [{X_scaled.min():.2f}, {X_scaled.max():.2f}]")
print(f"y_scaled range: [{y_scaled.min():.2f}, {y_scaled.max():.2f}]")
print(f"Original y example: {y.iloc[0]}")
print(f"Scaled y example: {y_scaled[0]:.4f}")

"""**Βήμα 6ο**: Ορισμός σταθερού seed"""

SEED = 42
print(f"Seed set to: {SEED}")

# Το Seed

"""**Βήμα 7ο**: Χωρισμός δεδομένων σε 6 Folds, με χρήση του KFold"""

from sklearn.model_selection import KFold

# n_splits=6: Χωρίζουμε τα δεδομένα σε 6 μέρη (folds), όπως ζητάει η εκφώνηση.
# shuffle=True: Ανακατεύουμε τα δεδομένα πριν τα χωρίσουμε.
# random_state=SEED: Χρησιμοποιούμε το seed που ορίσαμε στο βήμα 6.
kf = KFold(n_splits=6, shuffle=True, random_state=SEED)

# Δημιουργούμε μια λίστα που περιέχει τα indices (δείκτες) για κάθε fold.
# Χρησιμοποιούμε το X_scaled (ή το X, το ίδιο είναι για το πλήθος) για να βρει το KFold πόσες γραμμές έχουμε.
# Η εντολή list(kf.split(...)) εκτελεί το μοίρασμα εδώ και αποθηκεύει τους δείκτες.
fold_indices = list(kf.split(X_scaled))

print(f"K-Fold Indices Generated.")
print(f"Total splits created: {len(fold_indices)}")

print(f"--- K-Fold Cross Validation Setup (6 Folds) ---")

# Τυπώνουμε πληροφορίες για ΚΑΘΕ fold
for i, (train_idx, test_idx) in enumerate(fold_indices):
    print(f"\nFold {i}:")
    print(f"  - Train samples: {len(train_idx)} indices")
    print(f"  - Test samples:  {len(test_idx)} indices")
    # Τυπώνουμε τα πρώτα 5 indices για να βλέπουμε ότι είναι τυχαία και διαφορετικά
    print(f"  - First 5 Train Indices: {train_idx[:5]}")
    print(f"  - First 5 Test Indices:  {test_idx[:5]}")

# Επιβεβαίωση ότι ΔΕΝ υπάρχουν επικαλύψεις στο Test set (κάθε δείκτης πρέπει να εμφανίζεται 1 φορά ως Test)
all_test_indices = []
for _, test_idx in fold_indices:
    all_test_indices.extend(test_idx)

print(f"\nTotal unique test indices: {len(set(all_test_indices))} (Should be 442)")

# Η λίστα 'fold_indices' περιέχει μόνο ακέραιους αριθμούς (διευθύνσεις γραμμών).
# Δεν έχει γίνει replicate των δεδομένων

"""**Βήμα 8ο**: Δημιουργία λίστας csv_data, για καταχώρηση αποτελεσμάτων αργότερα."""

csv_data = []

# Προσθήκη της κεφαλίδας (Header row)
# Περιλαμβάνει τα metrics τόσο για τα κανονικοποιημένα (_n) όσο και για τα πραγματικά δεδομένα.
header = [
    "Model", "Set", "Fold",
    "Max_n", "RMSE_n", "MAE_n", "MAPE_n",
    "Max", "RMSE", "MAE", "MAPE"
]
csv_data.append(header)

print("--- CSV Data List Initialized ---")
print(f"Header created: {csv_data[0]}")

"""**Βήμα 9ο**: Εκπαίδευση μοντέλων

* Προετοιμασία και ορισμός μοντέλων
"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, WhiteKernel
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor

# Ορίζουμε ένα λεξικό (dictionary) που θα περιέχει:
# 1. Το όνομα του μοντέλου.
# 2. Το αντικείμενο του μοντέλου.
# 3. Το πλέγμα παραμέτρων (param_grid) για το RandomizedSearchCV.

model_setup = [
    {
        "name": "Random Forest",
        "model": RandomForestRegressor(random_state=SEED), # Βάζουμε SEED και εδώ
        "params": {
            # Πόσα δέντρα θα έχει το δάσος (π.χ. 50, 100 ή 200)
            "n_estimators": [50, 100, 200],
            # Το μέγιστο βάθος κάθε δέντρου (None σημαίνει απεριόριστο)
            "max_depth": [None, 10, 20, 30],
            # Ελάχιστα δείγματα για να χωριστεί ένας κόμβος
            "min_samples_split": [2, 5, 10]
        }
    },
    {
        "name": "Gaussian Process",
        # Το GPR θέλει έναν Kernel. Βάζουμε RBF (για την καμπύλη) + WhiteKernel (για τον θόρυβο).
        # Ο θόρυβος είναι απαραίτητος σε ιατρικά δεδομένα.
        "model": GaussianProcessRegressor(kernel=RBF() + WhiteKernel(), random_state=SEED),
        "params": {
            # Εδώ θα ψάξουμε την τιμή 'alpha' που διαχειρίζεται τον θόρυβο στις μετρήσεις
            "alpha": [1e-10, 1e-5, 1e-2, 0.1, 1.0],
            # Πόσες φορές θα επανεκκινήσει ο optimizer για να αποφύγει τοπικά ελάχιστα
            "n_restarts_optimizer": [0, 1, 2]
        }
    },
    {
        "name": "SVR", # Support Vector Regression (1η Επιλογή μας)
        "model": SVR(),
        "params": {
            # C: Πόσο αυστηρά τιμωρούμε τα λάθη (Regularization)
            "C": [0.1, 1, 10, 100],
            # kernel: Η μαθηματική συνάρτηση μετασχηματισμού
            "kernel": ["linear", "rbf", "poly"],
            # gamma: Πόσο επηρεάζει κάθε δείγμα (μόνο για rbf/poly)
            "gamma": ["scale", "auto"]
        }
    },
    {
        "name": "kNN", # k-Nearest Neighbors (2η Επιλογή μας)
        "model": KNeighborsRegressor(),
        "params": {
            # Πόσους γείτονες θα ρωτάμε (3, 5, 7, 9...)
            "n_neighbors": [3, 5, 7, 9, 11, 15],
            # Πώς θα ζυγίζουμε τη γνώμη τους (uniform=ίσα, distance=οι κοντινοί μετράνε πιο πολύ)
            "weights": ["uniform", "distance"]
        }
    }
]

print("Model configurations and hyperparameter grids are ready.")

"""**Βήματα**: 9a, 9b, 9c, 9d, 9e

Κατασκευή συνάρτησης για τον υπολογισμό μετρικών
"""

from sklearn.metrics import mean_squared_error, mean_absolute_error, max_error, mean_absolute_percentage_error

def calculate_metrics(y_true, y_pred):
    # Υπολογισμός
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_true, y_pred)
    max_err = max_error(y_true, y_pred)
    mape = mean_absolute_percentage_error(y_true, y_pred)

    return [max_err, rmse, mae, mape]

"""Δημιουργία φακέλου για εικόνες"""

import os
# Δημιουργία φακέλου για να αποθηκευτούν οι εικόνες
os.makedirs('plots', exist_ok=True)
print("Folder 'plots' created.")

"""Εκπαίδευση των μοντέλων και υπολογισμός καλύτερων υπερπαραμέτρων με την
RandomizedSearchCV
"""

from sklearn.model_selection import RandomizedSearchCV
import warnings

# Απενεργοποίηση προειδοποιήσεων (warnings) για καθαρή έξοδο
warnings.filterwarnings('ignore')

print("Starting Training Process")

# --- Outer Loop: Επανάληψη για κάθε Fold (0 έως 5) ---
for fold_id, (train_idx, test_idx) in enumerate(fold_indices):

    print(f"\n=== Processing Fold {fold_id} ===")

    # --- Βήμα 9a: Προετοιμασία Train/Test Data ---
    # Χρησιμοποιούμε τους δείκτες (indices) για να "κόψουμε" τα numpy arrays.
    # X_train_fold, y_train_fold: Τα δεδομένα που θα δει το μοντέλο για να μάθει.
    # X_test_fold, y_test_fold: Τα δεδομένα που θα κρατήσουμε κρυφά για το prediction.
    X_train_fold = X_scaled[train_idx]
    y_train_fold = y_scaled[train_idx]

    X_test_fold = X_scaled[test_idx]
    y_test_fold = y_scaled[test_idx]

    # --- Inner Loop: Επανάληψη για κάθε Μοντέλο ---
    for model_info in model_setup:
        model_name = model_info['name']
        base_model = model_info['model']
        param_grid = model_info['params']

        print(f"  > Tuning & Training {model_name}...")

        # --- Βήμα 9b: RandomizedSearchCV ---
        # Εδώ γίνεται η αναζήτηση των καλύτερων υπερπαραμέτρων.
        # n_iter=10: Θα δοκιμάσει 10 τυχαίους συνδυασμούς ρυθμίσεων.
        # cv=3: Εσωτερικό Cross-Validation (Nested CV). Το Train set χωρίζεται ξανά σε 3 μέρη
        #       για να βρεθεί η καλύτερη ρύθμιση, πριν εκπαιδευτεί στο σύνολο.
        # scoring: Προσπαθούμε να ελαχιστοποιήσουμε το λάθος (neg_mean_squared_error).
        random_search = RandomizedSearchCV(
            estimator=base_model,
            param_distributions=param_grid,
            n_iter=10,             # Αριθμός τυχαίων δοκιμών
            scoring='neg_mean_squared_error',
            cv=3,                  # 3-fold CV μέσα στο train set
            random_state=SEED,     # Για επαναληψιμότητα
            n_jobs=-1              # Χρήση όλων των πυρήνων του CPU για ταχύτητα
        )

        # Εκπαίδευση (Fit) πάνω στα TRAIN data του συγκεκριμένου fold
        random_search.fit(X_train_fold, y_train_fold)

        # Αποθήκευση του "νικητή" μοντέλου (best_estimator_)
        # Αυτό είναι το μοντέλο που θα χρησιμοποιήσουμε για προβλέψεις στο επόμενο βήμα.
        best_model = random_search.best_estimator_
        best_params = random_search.best_params_

        print(f"    - Best Params found: {best_params}")

        # --- Βήμα 9c: Prediction ---
        # Πρόβλεψη σε Train και Test (τιμές 0-1 ακόμα)
        y_pred_train_scaled = best_model.predict(X_train_fold)
        y_pred_test_scaled = best_model.predict(X_test_fold)

        # --- Βήμα 9d: Denormalize (Επαναφορά στο πραγματικό εύρος) ---

        # Η συνάρτηση inverse_transform του scaler θέλει δισδιάστατο πίνακα (2D array).
        # Γι' αυτό χρησιμοποιούμε το .reshape(-1, 1).
        # Μετά χρησιμοποιούμε το .flatten() για να το ξανακάνουμε απλή λίστα (1D).

        # 1. Για το Train Set (Πραγματικά και Προβλέψεις)
        y_train_real = scaler_y.inverse_transform(y_train_fold.reshape(-1, 1)).flatten()
        y_pred_train_real = scaler_y.inverse_transform(y_pred_train_scaled.reshape(-1, 1)).flatten()

        # 2. Για το Test Set (Πραγματικά και Προβλέψεις)
        # Αυτά θα χρησιμοποιήσουμε για την τελική αξιολόγηση
        y_test_real = scaler_y.inverse_transform(y_test_fold.reshape(-1, 1)).flatten()
        y_pred_test_real = scaler_y.inverse_transform(y_pred_test_scaled.reshape(-1, 1)).flatten()

        # --- Βήμα 9e: Υπολογισμός error metrics ---

        # 1. Υπολογισμός για Train Set (Normalized & Real)
        # Η συνάρτηση επιστρέφει λίστα [Max, RMSE, MAE, MAPE]
        train_metrics_n = calculate_metrics(y_train_fold, y_pred_train_scaled)
        train_metrics_r = calculate_metrics(y_train_real, y_pred_train_real)

        # 2. Υπολογισμός για Test Set (Normalized & Real)
        test_metrics_n = calculate_metrics(y_test_fold, y_pred_test_scaled)
        test_metrics_r = calculate_metrics(y_test_real, y_pred_test_real)

        # Εκτύπωση για έλεγχο (μόνο για το ένα μοντέλο σε κάθε fold για να μην γεμίσει η οθόνη)
        print(f"    > [Fold {fold_id} - {model_name}] Test Real: "
              f"RMSE={test_metrics_r[1]:.2f}, "   # Index 1
              f"MAE={test_metrics_r[2]:.2f}, "    # Index 2
              f"MAPE={test_metrics_r[3]:.2%}")    # Index 3 (μορφοποίηση ως ποσοστό %)

        # --- Βήμα 9f: Γράφημα Actual vs Predicted ---

        # Περιορίζουμε την εκτύπωση μόνο στο Fold 0
        # (Θα παραχθούν 4 γραφήματα, ένα για κάθε μοντέλο του Fold 0)
        if fold_id == 0:
            plt.figure(figsize=(6, 5))

            # 1. Τα σημεία (Scatter Plot)
            # Άξονας Χ: Πραγματικές Τιμές
            # Άξονας Υ: Προβλέψεις
            plt.scatter(y_test_real, y_pred_test_real, color='royalblue', alpha=0.6, label='Προβλέψεις')

            # 2. Η Ιδανική Γραμμή (Identity Line y=x)
            # Αν ένα σημείο πέσει πάνω στην κόκκινη γραμμή, σημαίνει Πρόβλεψη = Πραγματικότητα (Τέλειο)
            # Υπολογίζουμε τα όρια για να τραβήξουμε τη γραμμή από άκρη σε άκρη
            p_min = min(y_test_real.min(), y_pred_test_real.min())
            p_max = max(y_test_real.max(), y_pred_test_real.max())
            plt.plot([p_min, p_max], [p_min, p_max], 'r--', lw=2, label='Ιδανικό ταίριασμα')

            # Τίτλοι και Ετικέτες
            plt.title(f'Πραγματικές vs Προβλέψη - {model_name} (Fold {fold_id})')
            plt.xlabel('Πραγματικές Τιμές (mg/dL)')
            plt.ylabel('Τιμές πρόβλεψης (mg/dL)')
            plt.legend()
            plt.grid(True, alpha=0.3)

            # Αποθήκευση
            clean_name = model_name.replace(" ", "_")
            filename = f"plots/Fold{fold_id}_{clean_name}_ActualVsPred.png"
            plt.savefig(filename, bbox_inches='tight', dpi=300)

            # Εμφάνιση
            plt.show()


        # --- Βήμα 9g: Append στο csv data ---
        # Γραμμή Train: [Model, Set, Fold] + [Metrics_n] + [Metrics_r]
        # Το '+' ενώνει τις λίστες
        csv_data.append([model_name, "Train", fold_id] + train_metrics_n + train_metrics_r)

        # Γραμμή Test
        csv_data.append([model_name, "Test", fold_id] + test_metrics_n + test_metrics_r)

        # --- Βήμα 9h: SHAP Explainability ---

        if fold_id == 0:
            import shap

            shap.initjs()

            print(f"    > Generating SHAP plots for {model_name} (Fold 0)...")

            # 1. Δημιουργία του Explainer
            # Χρησιμοποιούμε ένα δείγμα (summary) του Train set για ταχύτητα,
            # αλλιώς το KernelExplainer θα είναι υπερβολικά αργό.
            # Το shap.sample παίρνει 50 τυχαία δείγματα από το train set ως "background".
            background_summary = shap.sample(X_train_fold, 50)

            # Δημιουργούμε τον explainer γενικής χρήσης.
            # Το best_model.predict είναι η συνάρτηση πρόβλεψης.
            explainer = shap.KernelExplainer(best_model.predict, background_summary)

            # 2. Υπολογισμός SHAP values για το TEST set
            # (Επιλέγουμε ένα μικρό κομμάτι του Test set για να μην αργήσει, π.χ. τα πρώτα 10 άτομα)
            X_test_sample = X_test_fold[:10]
            shap_values = explainer.shap_values(X_test_sample)

            # Καθαρό όνομα για το αρχείο
            clean_name = model_name.replace(" ", "_")

            # --- Plot 1: Summary Plot ---
            # Δείχνει ποια χαρακτηριστικά είναι τα πιο σημαντικά συνολικά.
            print(f"      [Plot] SHAP Summary Plot for {model_name}")
            plt.figure() # Νέο figure για να μην πέσει το ένα πάνω στο άλλο
            shap.summary_plot(shap_values, X_test_sample, feature_names=df.drop(columns=['target']).columns, show=False)

            filename_sum = f"plots/Fold{fold_id}_{clean_name}_SHAP_Summary.png"
            plt.savefig(filename_sum, bbox_inches='tight', dpi=300)
            plt.show()

            # --- Plot 2: Waterfall Plots (για 2 παραδείγματα) ---
            # Θα πάρουμε τον πρώτο (index 0) και τον δεύτερο (index 1) ασθενή από το test sample.

            # Το KernelExplainer επιστρέφει np.array, αλλά το waterfall θέλει αντικείμενο Explanation.
            # Φτιάχνουμε το αντικείμενο Explanation χειροκίνητα για συμβατότητα.
            explanation = shap.Explanation(
                values=shap_values,
                base_values=explainer.expected_value,
                data=X_test_sample,
                feature_names=df.drop(columns=['target']).columns
            )

            # Παράδειγμα 1 (Ασθενής 0)
            print(f"      [Plot] SHAP Waterfall Plot for Patient 0 ({model_name})")
            plt.figure()
            shap.plots.waterfall(explanation[0], show=False)

            filename_wf1 = f"plots/Fold{fold_id}_{clean_name}_SHAP_Waterfall_Pat0.png"
            plt.savefig(filename_wf1, bbox_inches='tight', dpi=300)

            plt.show()

            # Παράδειγμα 2 (Ασθενής 1)
            print(f"      [Plot] SHAP Waterfall Plot for Patient 1 ({model_name})")
            plt.figure()
            shap.plots.waterfall(explanation[1], show=False)

            filename_wf2 = f"plots/Fold{fold_id}_{clean_name}_SHAP_Waterfall_Pat1.png"
            plt.savefig(filename_wf2, bbox_inches='tight', dpi=300)

            plt.show()

"""Αποθήκευση αποτελεσμάτων στο csv"""

# --- Δημιουργία DataFrame και Εξαγωγή ---

# Μετατρέπουμε τη λίστα λιστών (csv_data) σε Pandas DataFrame
# Η πρώτη γραμμή της λίστας περιέχει τα ονόματα των στηλών (Headers)
results_df = pd.DataFrame(csv_data[1:], columns=csv_data[0])

# Αποθηκεύουμε σε αρχείο CSV
filename = "diabetes_model_results.csv"
results_df.to_csv(filename, index=False)
print(f"Results saved to file: {filename}")

# --- Εμφάνιση των αποτελεσμάτων ---
print("\n--- Detailed Results (First 10 rows) ---")
# Τυπώνουμε τις πρώτες γραμμές για να δούμε τη μορφή
print(results_df.head(10))


# Ο πίνακας έχει πολλές γραμμές (6 folds x 4 μοντέλα x 2 sets = 48 γραμμές).

# Φιλτράρουμε μόνο τις γραμμές του Test set
test_results = results_df[results_df["Set"] == "Test"]

# Μετατρέπουμε τις στήλες με νούμερα σε αριθμητική μορφή
cols_to_mean = ["RMSE", "MAE", "MAPE", "Max"]
for col in cols_to_mean:
    test_results[col] = pd.to_numeric(test_results[col])

# Ομαδοποίηση ανά Μοντέλο και υπολογισμός Μέσου Όρου
summary = test_results.groupby("Model")[cols_to_mean].mean()

print("\n--- Average Performance on Test Set (All 6 Folds) ---")
print(summary)